### ISSUE TITLE
readme使用声明建议

### ISSUE THREAD

**Issue by Nambers** [Haojen/hexo-theme-Claudia#57]
在执行readme里安装时报错
```
D:\hexo\hexo>npm install --save hexo-renderer-sass
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path D:\hexo\hexo\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@12.13.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: D:\Anaconda3\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                                ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "D:\\nodejs\\node.exe" "D:\\hexo\\hexo\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\hexo\hexo\node_modules\node-sass
npm ERR! gyp ERR! node -v v12.13.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
```
怀疑是依赖库版本已经不再支持了？或者是我npm源配置或版本问题?

**Comment by Nambers** [comment]
应该是node v12的问题 https://stackoverflow.com/questions/56016794/can-not-install-node-gyp

**Comment by Nambers** [comment]
上面问题解决了，装node v14.16就可以了，然后有另外一个问题，就执行完依赖下载，themes文件夹下没有东西？就没有主题的文件或_config.yml

**Comment by Nambers** [comment]
tcl 忘记下项目根目录文件放到themes里了，明白了，建议把这个加到那些命令前面吧
